### ISSUE TITLE
Move configuration to system settings

### ISSUE THREAD

**Issue by wuuti** [BobRay/UpgradeMODX#15]
The configuration of UpgradeModx should be possible with system settings instead of properties for a snippet.

**Comment by BobRay** [comment]
Can you explain why you would want this?  Most MODX extras don't use System Settings unless they need to or those System Settings need to be available across the site.

**Comment by inreti** [comment]
Well, having the settings as properties for a snippet is not intuitive. Even for me as an experienced user - I had to find and read the docs to realize where to tweak upgrademodx's settings. Properties for a snippet to configure a separate script triggered by a dashboard widget? Does not sound very logical imho. And your extra is more than just this snippet, so system-wide, namespaced setting would better I believe. 
And - to be honest - it is the first time ever I saw an extra being configured with properties like that...

**Comment by sebastian-marinescu** [comment]
I've seen this many times on small Extras. 
But I am also not a big fan of it. It just seems 'hidden' and is unexpected.

That is why I'd also prefer the system-settings - in general for all Extras. 
I don't see any additional benefit from using properties, if it doesn't make sense to use property-sets.

Or are there any use-cases where a different property-set in this Extra would be helpful @BobRay ?

**Comment by BobRay** [comment]
Widgets don't take property sets, so there's no use-case for that here.

I thought seriously about doing this, and I agree that it would probably have been better to do it this way to begin with. But the upgrade would break UGM for some people,  unless I read the values of the their current properties and set the System Settings with them. This is problematical, because if the snippet is installed without properties (which it would have to be for the System Settings to have any effect), the values of their properties would be lost before I could read them in a resolver.

In addition, people are used to setting the properties and would have to read the manual to find out where they've gone. 

People only have to read the docs once to find them, and the docs really should be read at least once anyway.
