### ISSUE TITLE
Weird font sizes?

### ISSUE THREAD

**Issue by SnowCreative** [BobRay/UpgradeMODX#71]
I'm wondering why the font size is set in your CSS to increase to 200% when the browser width is less than 1300px. It looks kind of weird, and I don't think this happened in previous versions:

![Screen Shot 2021-05-31 at 4 08 13 PM](https://user-images.githubusercontent.com/2528374/120238806-f6cd5980-c22a-11eb-97d0-7e9c1463b534.png)

**Comment by BobRay** [comment]
I don't think that's changed between versions, but I could be wrong. 

CSS based on media queries tends to be a compromise between usability and visual attractiveness. I think the point of this one was to make it easier to use for people with fat fingers and/or poor eyesight.  ;)  

It's problematic because the titles are so long and the space allocated by the Manager layout is somewhat narrow. I didn't want to waste Manager space by making it full width.

**Comment by SnowCreative** [comment]
So, maybe trigger the change at a much smaller screen width? 1300 pixels is still desktop size, so I don't think many people will be using their fingers yet!

**Comment by BobRay** [comment]
"1300 pixels is still desktop size"

Right, but it's also the size of some tablets, including the original iPad, and most tablets in portrait orientation. My desktop is 1920 pixels wide, so I'm somewhat spoiled. 

What's your recommendation for the pixel width?

**Comment by SnowCreative** [comment]
I guess laptop screen sizes have increased. Used to be that 1280 was a standard break point. My monitor is 1920 wide, too, but I don't keep my browsers that wide. And what about on an iPad pro? At 1366 pixels wide, that means the smaller type size will apply. Tablet and laptop sizes have kind of converged. Sure is nice to have CSS-only style sheets, but maybe we need to start querying for the device and load custom media queries if it's actually a mobile device? Not exactly what I want to spend me time doing.

**Comment by BobRay** [comment]
Me too. ;)
